# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 50aece1468c676048e62c9e2b3679b81a0884e80ea6364c83609f6724389cd57fdb99e78c85d61834ab8658235d87a38967dc5e7a0a8bc0f94638e9732bcadde

test:
  secret_key_base: 3fc4fc24632b2ca2fbdaaff268e293ebe6d87f311ea72596f7d016cc1453c7d82b7d074a598255fc1555a73edb3fd1a1c2862dd025614240d056f375c21187ea

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
